<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c823c65a-a79e-4871-a3fc-2ca5736d9777</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KHost.UserInterface\KHost.UserInterface.csproj" />
  </ItemGroup>

</Project>
