// <auto-generated />
using System;
using KHost.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KHost.DataAccess.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("KHost.Abstractions.Models.KHostUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KHost.Abstractions.Models.KHostUserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Full access to all management features",
                            IsAdmin = true,
                            Name = "Admin",
                            Permissions = "[]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Frequent singer",
                            IsAdmin = false,
                            Name = "Regular",
                            Permissions = "[]"
                        });
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artist");

                    b.HasIndex("DateAdded");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SingerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("MediaId");

                    b.HasIndex("SingerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Tip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("Tips");
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("KHost.DataAccess.Models.UserGroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMemberships", (string)null);
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Tip", b =>
                {
                    b.HasOne("KHost.Abstractions.Models.KHostUser", null)
                        .WithMany("Tips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KHost.Abstractions.Models.Venue", b =>
                {
                    b.OwnsOne("KHost.Abstractions.Models.Venue+VenueSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("VenueId");

                            b1.Property<bool>("ClearQueueOnClose");

                            b1.Property<int>("DefaultVolume");

                            b1.Property<int>("DuplicateSongWindowHours");

                            b1.Property<int>("OnScreenDisconnect");

                            b1.Property<bool>("PromptBeforeRemovingPerformance");

                            b1.Property<bool>("PromptBeforeRemovingSinger");

                            b1.Property<bool>("ShowEstimatedWaitTime");

                            b1.Property<bool>("TippingEnabled");

                            b1.Property<bool>("WarnOnDuplicateSong");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venues");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");

                            b1.OwnsOne("KHost.Plugins.Sdk.Models.QueueRotation.QueueRotationConfig", "QueueRotation", b2 =>
                                {
                                    b2.Property<Guid>("VenueSettingsVenueId");

                                    b2.Property<int>("CoolDownSlots");

                                    b2.Property<int>("DropFixedIndex");

                                    b2.Property<int>("DropPosition");

                                    b2.Property<bool>("FirstTimeBoostEnabled");

                                    b2.Property<int>("FirstTimeBoostSlots");

                                    b2.Property<string>("StrategyId")
                                        .IsRequired();

                                    b2.Property<Guid?>("VipGroupId");

                                    b2.Property<double>("WeightedFairSongCountWeight");

                                    b2.Property<double>("WeightedFairWaitWeight");

                                    b2.HasKey("VenueSettingsVenueId");

                                    b2.ToTable("Venues");

                                    b2.WithOwner()
                                        .HasForeignKey("VenueSettingsVenueId");
                                });

                            b1.Navigation("QueueRotation");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("KHost.DataAccess.Models.UserGroupMembership", b =>
                {
                    b.HasOne("KHost.Abstractions.Models.KHostUserGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KHost.Abstractions.Models.KHostUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KHost.Abstractions.Models.KHostUser", b =>
                {
                    b.Navigation("Tips");
                });
#pragma warning restore 612, 618
        }
    }
}
