<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Unidecode.NET" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>KHost.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KHost.Common\KHost.Common.csproj" />
    <ProjectReference Include="..\KHost.Abstractions\KHost.Abstractions.csproj" />
    <ProjectReference Include="..\KHost.LrcLib\KHost.LrcLib.csproj" />
    <ProjectReference Include="..\KHost.Telemetry\KHost.Telemetry.csproj" />
  </ItemGroup>

</Project>
